#1.Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.
import numpy as np

In [17]:
arr = np.arange(1,11)

In [20]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr1=arr.reshape(2,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#2.Create a numpy array containing the numbers from 1 to 20, and then extract the elements between
# the 5th and 15th index
 .

In [26]:
arr2 =np.arange(1,21)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
elements = arr2[5:15]
elements

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
#3.Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a
# new item to the series with the key 'pears' and the value 4.


In [1]:
import pandas as pd

fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

fruit_series['pears'] = 4
print(fruit_series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [ ]:
# 4.Create a dataframe with the following columns: name, age, and gender. The dataframe should have
# 10 rows of data.

In [3]:
import pandas as pd
details = {
     'name': ['Emy', 'Linz', 'Christy', 'David', 'Evana',
              'John', 'Ruth', 'Rebeca', 'Brown', 'Jasmine'],
     'age': [23, 34, 45, 29, 31,
             22, 36, 27, 40, 35],
     'gender': ['Female', 'Male', 'Male', 'Male', 'Female',
                'Male', 'Female', 'Female', 'Male', 'Female']
 }

df= pd.DataFrame(details)
print(df)

      name  age  gender
0      Emy   23  Female
1     Linz   34    Male
2  Christy   45    Male
3    David   29    Male
4    Evana   31  Female
5     John   22    Male
6     Ruth   36  Female
7   Rebeca   27  Female
8    Brown   40    Male
9  Jasmine   35  Female


In [ ]:
#5.Add a new column to the data frame created in question 1, called occupation. The values for this
#column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [15]:
import pandas as pd

details = {
    'name': ['Emy', 'Linz', 'Christy', 'David', 'Evana',
             'John', 'Ruth', 'Rebeca', 'Brown', 'Jasmine'],
     'age': [23, 34, 45, 29, 31,  
             22, 36, 27, 40, 35],
     'gender': ['Female', 'Male', 'Male', 'Male', 'Female',
                'Male', 'Female', 'Female', 'Male', 'Female'],
     'occupation': ['Programmer', 'Manager', 'Analyst', 'Programmer',
                    'Manager', 'Analyst', 'Programmer', 'Manager',
                    'Analyst', 'Programmer']
   }
df1 = pd.DataFrame(details)
print(df1)

      name  age  gender  occupation
0      Emy   23  Female  Programmer
1     Linz   34    Male     Manager
2  Christy   45    Male     Analyst
3    David   29    Male  Programmer
4    Evana   31  Female     Manager
5     John   22    Male     Analyst
6     Ruth   36  Female  Programmer
7   Rebeca   27  Female     Manager
8    Brown   40    Male     Analyst
9  Jasmine   35  Female  Programmer


In [ ]:
#6.Select the rows of the dataframe where the age is greater than or equal to 30.

In [17]:
filtered_df = df[df1['age'] >= 30]
print(filtered_df)


      name  age  gender
1     Linz   34    Male
2  Christy   45    Male
4    Evana   31  Female
6     Ruth   36  Female
8    Brown   40    Male
9  Jasmine   35  Female


In [ ]:
#7.Convert this dataframe to a csv file and read that csv file, finally display the contents

In [37]:

import pandas as pd
df1 = pd.DataFrame(details)

csv_file_path = 'details.csv'#converting the DataFrame to csv file
df.to_csv(csv_file_path, index=False)

In [39]:
df_read = pd.read_csv( csv_file_path)   #"C:\Users\sgkur\details.csv"
print(df_read)

      name  age  gender
0      Emy   23  Female
1     Linz   34    Male
2  Christy   45    Male
3    David   29    Male
4    Evana   31  Female
5     John   22    Male
6     Ruth   36  Female
7   Rebeca   27  Female
8    Brown   40    Male
9  Jasmine   35  Female
